const companies = [
  { symbol: "MMM", name: "3M", alias: [] },
  { symbol: "AOS", name: "A. O. Smith", alias: [] },
  { symbol: "ABT", name: "Abbott", alias: [] },
  { symbol: "ABBV", name: "AbbVie", alias: [] },
  { symbol: "ACN", name: "Accenture", alias: [] },
  { symbol: "ADBE", name: "Adobe Inc.", alias: [] },
  { symbol: "AMD", name: "AMD", alias: ["Advanced Micro Devices"] },
  { symbol: "AES", name: "AES Corporation", alias: ["AES"] },
  { symbol: "AFL", name: "Aflac", alias: [] },
  { symbol: "A", name: "Agilent Technologies", alias: [] },
  { symbol: "APD", name: "Air Products and Chemicals", alias: [] },
  { symbol: "ABNB", name: "Airbnb", alias: [] },
  { symbol: "AKAM", name: "Akamai", alias: [] },
  { symbol: "ALB", name: "Albemarle", alias: [] },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", alias: [] },
  { symbol: "ALGN", name: "Align Technology", alias: [] },
  { symbol: "ALLE", name: "Allegion", alias: [] },
  { symbol: "LNT", name: "Alliant Energy", alias: [] },
  { symbol: "ALL", name: "Allstate", alias: [] },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", alias: ["Google", "Alphabet"] },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", alias: ["Google Class C", "Alphabet C"] },
  { symbol: "MO", name: "Altria", alias: [] },
  { symbol: "AMZN", name: "Amazon", alias: [] },
  { symbol: "AMCR", name: "Amcor", alias: [] },
  { symbol: "AEE", name: "Ameren", alias: [] },
  { symbol: "AAL", name: "American Airlines", alias: [] },
  { symbol: "AEP", name: "American Electric Power", alias: [] },
  { symbol: "AXP", name: "American Express", alias: [] },
  { symbol: "AIG", name: "American International Group", alias: ["AIG"] },
  { symbol: "AMT", name: "American Tower", alias: [] },
  { symbol: "AWK", name: "American Water Works", alias: [] },
  { symbol: "AMP", name: "Ameriprise Financial", alias: [] },
  { symbol: "AME", name: "Ametek", alias: [] },
  { symbol: "AMGN", name: "Amgen", alias: [] },
  { symbol: "APH", name: "Amphenol", alias: [] },
  { symbol: "ADI", name: "Analog Devices", alias: [] },
  { symbol: "ANSS", name: "Ansys", alias: [] },
  { symbol: "AON", name: "Aon", alias: [] },
  { symbol: "APA", name: "APA Corporation", alias: ["APA"] },
  { symbol: "AAPL", name: "Apple", alias: [] },
  { symbol: "AMAT", name: "Applied Materials", alias: [] },
  { symbol: "APTV", name: "Aptiv PLC", alias: ["Aptiv"] },
  { symbol: "ACGL", name: "Arch Capital Group", alias: [] },
  { symbol: "ADM", name: "Archer-Daniels-Midland", alias: [] },
  { symbol: "ANET", name: "Arista Networks", alias: [] },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", alias: ["Arthur J. Gallagher"] },
  { symbol: "AIZ", name: "Assurant", alias: [] },
  { symbol: "T", name: "AT&T", alias: [] },
  { symbol: "ATO", name: "Atmos Energy", alias: [] },
  { symbol: "ADSK", name: "Autodesk", alias: [] },
  { symbol: "ADP", name: "Automatic Data Processing", alias: ["ADP"] },
  { symbol: "AZO", name: "AutoZone", alias: [] },
  { symbol: "AVB", name: "AvalonBay Communities", alias: [] },
  { symbol: "AVY", name: "Avery Dennison", alias: [] },
  { symbol: "AXON", name: "Axon Enterprise", alias: [] },
  { symbol: "BKR", name: "Baker Hughes", alias: [] },
  { symbol: "BALL", name: "Ball Corporation", alias: [] },
  { symbol: "BAC", name: "Bank of America", alias: [] },
  { symbol: "BK", name: "Bank of New York Mellon", alias: ["BNY Mellon"] },
  { symbol: "BBWI", name: "Bath & Body Works, Inc.", alias: [] },
  { symbol: "BAX", name: "Baxter International", alias: [] },
  { symbol: "BDX", name: "Becton Dickinson", alias: [] },
  { symbol: "BRK.B", name: "Berkshire Hathaway", alias: [] },
  { symbol: "BBY", name: "Best Buy", alias: [] },
  { symbol: "BIO", name: "Bio-Rad", alias: [] },
  { symbol: "TECH", name: "Bio-Techne", alias: [] },
  { symbol: "BIIB", name: "Biogen", alias: [] },
  { symbol: "BLK", name: "BlackRock", alias: [] },
  { symbol: "BX", name: "Blackstone", alias: [] },
  { symbol: "BA", name: "Boeing", alias: [] },
  { symbol: "BKNG", name: "Booking Holdings", alias: [] },
  { symbol: "BWA", name: "BorgWarner", alias: [] },
  { symbol: "BXP", name: "Boston Properties", alias: [] },
  { symbol: "BSX", name: "Boston Scientific", alias: [] },
  { symbol: "BMY", name: "Bristol Myers Squibb", alias: [] },
  { symbol: "AVGO", name: "Broadcom", alias: [] },
  { symbol: "BR", name: "Broadridge Financial Solutions", alias: ["Broadridge"] },
  { symbol: "BRO", name: "Brown & Brown", alias: [] },
  { symbol: "BF.B", name: "Brown–Forman", alias: [] },
  { symbol: "BLDR", name: "Builders FirstSource", alias: [] },
  { symbol: "BG", name: "Bunge Global SA", alias: [] },
  { symbol: "CDNS", name: "Cadence Design Systems", alias: [] },
  { symbol: "CZR", name: "Caesars Entertainment", alias: [] },
  { symbol: "CPT", name: "Camden Property Trust", alias: [] },
  { symbol: "CPB", name: "Campbell Soup", alias: ["Campbell Soup Company"] },
  { symbol: "COF", name: "Capital One", alias: [] },
  { symbol: "CAH", name: "Cardinal Health", alias: [] },
  { symbol: "KMX", name: "CarMax", alias: [] },
  { symbol: "CCL", name: "Carnival", alias: [] },
  { symbol: "CARR", name: "Carrier Global", alias: [] },
  { symbol: "CTLT", name: "Catalent", alias: [] },
  { symbol: "CAT", name: "Caterpillar Inc.", alias: [] },
  { symbol: "CBOE", name: "Cboe Global Markets", alias: [] },
  { symbol: "CBRE", name: "CBRE Group", alias: [] },
  { symbol: "CDW", name: "CDW", alias: [] },
  { symbol: "CE", name: "Celanese", alias: [] },
  { symbol: "COR", name: "Cencora", alias: [] },
  { symbol: "CNC", name: "Centene Corporation", alias: ["Centene"] },
  { symbol: "CNP", name: "CenterPoint Energy", alias: [] },
  { symbol: "CF", name: "CF Industries", alias: [] },
  { symbol: "CHRW", name: "CH Robinson", alias: ["CHRW"] },
  { symbol: "CRL", name: "Charles River Laboratories", alias: ["Charles River"] },
  { symbol: "SCHW", name: "Charles Schwab Corporation", alias: [] },
  { symbol: "CHTR", name: "Charter Communications", alias: [] },
  { symbol: "CVX", name: "Chevron Corporation", alias: ["Chevron"] },
  { symbol: "CMG", name: "Chipotle Mexican Grill", alias: ["Chipotle"] },
  { symbol: "CB", name: "Chubb Limited", alias: ["Chubb"] },
  { symbol: "CHD", name: "Church & Dwight", alias: [] },
  { symbol: "CI", name: "Cigna", alias: [] },
  { symbol: "CINF", name: "Cincinnati Financial", alias: [] },
  { symbol: "CTAS", name: "Cintas", alias: [] },
  { symbol: "CSCO", name: "Cisco", alias: [] },
  { symbol: "C", name: "Citigroup", alias: [] },
  { symbol: "CFG", name: "Citizens Financial Group", alias: [] },
  { symbol: "CLX", name: "Clorox", alias: [] },
  { symbol: "CME", name: "CME Group", alias: [] },
  { symbol: "CMS", name: "CMS Energy", alias: [] },
  { symbol: "KO", name: "Coca-Cola Company", alias: ["Coca-Cola"] },
  { symbol: "CTSH", name: "Cognizant", alias: [] },
  { symbol: "CL", name: "Colgate-Palmolive", alias: [] },
  { symbol: "CMCSA", name: "Comcast", alias: [] },
  { symbol: "CMA", name: "Comerica", alias: [] },
  { symbol: "CAG", name: "Conagra Brands", alias: ["Conagra"] },
  { symbol: "COP", name: "ConocoPhillips", alias: [] },
  { symbol: "ED", name: "Consolidated Edison", alias: ["Con Edison"] },
  { symbol: "STZ", name: "Constellation Brands", alias: [] },
  { symbol: "CEG", name: "Constellation Energy", alias: [] },
  { symbol: "COO", name: "Cooper Companies", alias: ["Cooper"] },
  { symbol: "CPRT", name: "Copart", alias: [] },
  { symbol: "GLW", name: "Corning", alias: [] },
  { symbol: "CPAY", name: "Corpay", alias: [] },
  { symbol: "CTVA", name: "Corteva", alias: [] },
  { symbol: "CSGP", name: "CoStar Group", alias: ["CoStar"] },
  { symbol: "COST", name: "Costco Wholesale", alias: ["COSTCO"] },
  { symbol: "CTRA", name: "Coterra", alias: [] },
  { symbol: "CCI", name: "Crown Castle", alias: [] },
  { symbol: "CSX", name: "CSX", alias: [] },
  { symbol: "CMI", name: "Cummins", alias: [] },
  { symbol: "CVS", name: "CVS Health", alias: [] },
  { symbol: "DHR", name: "Danaher Corporation", alias: ["Danaher"] },
  { symbol: "DRI", name: "Darden Restaurants", alias: [] },
  { symbol: "DVA", name: "DaVita Inc.", alias: [] },
  { symbol: "DAY", name: "Dayforce", alias: [] },
  { symbol: "DECK", name: "Deckers Outdoor", alias: ["Deckers Brands"] },
  { symbol: "DE", name: "John Deere", alias: ["Deere & Company"] },
  { symbol: "DAL", name: "Delta Air Lines", alias: ["Delta"] },
  { symbol: "DVN", name: "Devon Energy", alias: [] },
  { symbol: "DXCM", name: "Dexcom", alias: [] },
  { symbol: "FANG", name: "Diamondback Energy", alias: [] },
  { symbol: "DLR", name: "Digital Realty", alias: [] },
  { symbol: "DFS", name: "Discover Financial", alias: [] },
  { symbol: "DG", name: "Dollar General", alias: [] },
  { symbol: "DLTR", name: "Dollar Tree", alias: [] },
  { symbol: "D", name: "Dominion Energy", alias: [] },
  { symbol: "DPZ", name: "Domino's", alias: [] },
  { symbol: "DOV", name: "Dover Corporation", alias: [] },
  { symbol: "DOW", name: "Dow Inc.", alias: ["Dow"] },
  { symbol: "DHI", name: "DR Horton", alias: ["DHI"] },
  { symbol: "DTE", name: "DTE Energy", alias: [] },
  { symbol: "DUK", name: "Duke Energy", alias: [] },
  { symbol: "DD", name: "DuPont", alias: [] },
  { symbol: "EMN", name: "Eastman Chemical", alias: [] },
  { symbol: "ETN", name: "Eaton Corporation", alias: ["Eaton"] },
  { symbol: "EBAY", name: "eBay", alias: [] },
  { symbol: "ECL", name: "Ecolab", alias: [] },
  { symbol: "EIX", name: "Edison International", alias: ["Edison"] },
  { symbol: "EW", name: "Edwards Lifesciences", alias: [] },
  { symbol: "EA", name: "Electronic Arts", alias: [] },
  { symbol: "ELV", name: "Elevance Health", alias: [] },
  { symbol: "LLY", name: "Eli Lilly and Company", alias: [] },
  { symbol: "EMR", name: "Emerson Electric", alias: [] },
  { symbol: "ENPH", name: "Enphase Energy", alias: ["Enphase"] },
  { symbol: "ETR", name: "Entergy", alias: [] },
  { symbol: "EOG", name: "EOG Resources", alias: [] },
  { symbol: "EPAM", name: "EPAM Systems", alias: [] },
  { symbol: "EQT", name: "EQT Corporation", alias: [] },
  { symbol: "EFX", name: "Equifax", alias: [] },
  { symbol: "EQIX", name: "Equinix", alias: [] },
  { symbol: "EQR", name: "Equity Residential", alias: [] },
  { symbol: "ESS", name: "Essex Property Trust", alias: ["Essex Property"] },
  { symbol: "EL", name: "Estée Lauder", alias: [] },
  { symbol: "ETSY", name: "Etsy", alias: [] },
  { symbol: "EG", name: "Everest Re", alias: [] },
  { symbol: "EVRG", name: "Evergy", alias: [] },
  { symbol: "ES", name: "Eversource", alias: [] },
  { symbol: "EXC", name: "Exelon", alias: [] },
  { symbol: "EXPE", name: "Expedia Group", alias: [] },
  { symbol: "EXPD", name: "Expeditors International", alias: ["Expeditors"] },
  { symbol: "EXR", name: "Extra Space Storage", alias: [] },
  { symbol: "XOM", name: "ExxonMobil", alias: [] },
  { symbol: "FFIV", name: "F5, Inc.", alias: ["F5 Networks"] },
  { symbol: "FDS", name: "FactSet", alias: [] },
  { symbol: "FICO", name: "Fair Isaac", alias: [] },
  { symbol: "FAST", name: "Fastenal", alias: [] },
  { symbol: "FRT", name: "Federal Realty", alias: [] },
  { symbol: "FDX", name: "FedEx", alias: [] },
  { symbol: "FIS", name: "Fidelity National Information Services", alias: ["FIS"] },
  { symbol: "FITB", name: "Fifth Third Bank", alias: [] },
  { symbol: "FSLR", name: "First Solar", alias: [] },
  { symbol: "FE", name: "FirstEnergy", alias: [] },
  { symbol: "FI", name: "Fiserv", alias: [] },
  { symbol: "FMC", name: "FMC Corporation", alias: ["FMC"] },
  { symbol: "F", name: "Ford Motor Company", alias: ["Ford"] },
  { symbol: "FTNT", name: "Fortinet", alias: [] },
  { symbol: "FTV", name: "Fortive", alias: [] },
  { symbol: "FOXA", name: "Fox Corporation (Class A)", alias: ["Fox"] },
  { symbol: "FOX", name: "Fox Corporation (Class B)", alias: ["Fox B"] },
  { symbol: "BEN", name: "Franklin Templeton", alias: [] },
  { symbol: "FCX", name: "Freeport-McMoRan", alias: [] },
  { symbol: "GRMN", name: "Garmin", alias: [] },
  { symbol: "IT", name: "Gartner", alias: [] },
  { symbol: "GE", name: "GE Aerospace", alias: [] },
  { symbol: "GEHC", name: "GE HealthCare", alias: [] },
  { symbol: "GEV", name: "GE Vernova", alias: [] },
  { symbol: "GEN", name: "Gen Digital", alias: [] },
  { symbol: "GNRC", name: "Generac", alias: [] },
  { symbol: "GD", name: "General Dynamics", alias: [] },
  { symbol: "GIS", name: "General Mills", alias: [] },
  { symbol: "GM", name: "General Motors", alias: [] },
  { symbol: "GPC", name: "Genuine Parts", alias: [] },
  { symbol: "GILD", name: "Gilead Sciences", alias: [] },
  { symbol: "GPN", name: "Global Payments", alias: [] },
  { symbol: "GL", name: "Globe Life", alias: [] },
  { symbol: "GS", name: "Goldman Sachs", alias: [] },
  { symbol: "HAL", name: "Halliburton", alias: [] },
  { symbol: "HIG", name: "Hartford", alias: [] },
  { symbol: "HAS", name: "Hasbro", alias: [] },
  { symbol: "HCA", name: "HCA Healthcare", alias: [] },
  { symbol: "DOC", name: "Healthpeak", alias: [] },
  { symbol: "HSIC", name: "Henry Schein", alias: [] },
  { symbol: "HSY", name: "Hershey", alias: [] },
  { symbol: "HES", name: "Hess Corporation", alias: ["Hess"] },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", alias: [] },
  { symbol: "HLT", name: "Hilton Worldwide", alias: [] },
  { symbol: "HOLX", name: "Hologic", alias: [] },
  { symbol: "HD", name: "Home Depot", alias: [] },
  { symbol: "HON", name: "Honeywell", alias: [] },
  { symbol: "HRL", name: "Hormel Foods", alias: [] },
  { symbol: "HST", name: "Host Hotels & Resorts", alias: ["Host Hotels"] },
  { symbol: "HWM", name: "Howmet Aerospace", alias: [] },
  { symbol: "HPQ", name: "HP Inc.", alias: ["HP"] },
  { symbol: "HUBB", name: "Hubbell Incorporated", alias: [] },
  { symbol: "HUM", name: "Humana", alias: [] },
  { symbol: "HBAN", name: "Huntington Bancshares", alias: [] },
  { symbol: "HII", name: "Huntington Ingalls Industries", alias: ["Huntington Ingalls"] },
  { symbol: "IBM", name: "IBM", alias: ["International Business Machines"] },
  { symbol: "IEX", name: "IDEX Corporation", alias: ["IDEX"] },
  { symbol: "IDXX", name: "Idexx Laboratories", alias: ["Idexx"] },
  { symbol: "ITW", name: "Illinois Tool Works", alias: [] },
  { symbol: "ILMN", name: "Illumina", alias: [] },
  { symbol: "INCY", name: "Incyte", alias: [] },
  { symbol: "IR", name: "Ingersoll Rand", alias: [] },
  { symbol: "PODD", name: "Insulet", alias: [] },
  { symbol: "INTC", name: "Intel", alias: [] },
  { symbol: "ICE", name: "Intercontinental Exchange", alias: [] },
  { symbol: "IFF", name: "International Flavors & Fragrances", alias: [] },
  { symbol: "IP", name: "International Paper", alias: [] },
  { symbol: "IPG", name: "Interpublic Group", alias: [] },
  { symbol: "INTU", name: "Intuit", alias: [] },
  { symbol: "ISRG", name: "Intuitive Surgical", alias: [] },
  { symbol: "IVZ", name: "Invesco", alias: [] },
  { symbol: "INVH", name: "Invitation Homes", alias: [] },
  { symbol: "IQV", name: "IQVIA", alias: [] },
  { symbol: "IRM", name: "Iron Mountain", alias: [] },
  { symbol: "JBHT", name: "J.B. Hunt", alias: [] },
  { symbol: "JBL", name: "Jabil", alias: [] },
  { symbol: "JKHY", name: "Jack Henry & Associates", alias: ["Jack Henry"] },
  { symbol: "J", name: "Jacobs Solutions", alias: [] },
  { symbol: "JNJ", name: "Johnson & Johnson", alias: [] },
  { symbol: "JCI", name: "Johnson Controls", alias: [] },
  { symbol: "JPM", name: "JPMorgan Chase", alias: [] },
  { symbol: "JNPR", name: "Juniper Networks", alias: [] },
  { symbol: "K", name: "Kellanova", alias: [] },
  { symbol: "KVUE", name: "Kenvue", alias: [] },
  { symbol: "KDP", name: "Keurig Dr Pepper", alias: [] },
  { symbol: "KEY", name: "KeyCorp", alias: [] },
  { symbol: "KEYS", name: "Keysight", alias: [] },
  { symbol: "KMB", name: "Kimberly-Clark", alias: [] },
  { symbol: "KIM", name: "Kimco Realty", alias: [] },
  { symbol: "KMI", name: "Kinder Morgan", alias: [] },
  { symbol: "KLAC", name: "KLA Corporation", alias: [] },
  { symbol: "KHC", name: "Kraft Heinz", alias: [] },
  { symbol: "KR", name: "Kroger", alias: [] },
  { symbol: "LHX", name: "L3Harris", alias: [] },
  { symbol: "LH", name: "LabCorp", alias: [] },
  { symbol: "LRCX", name: "Lam Research", alias: [] },
  { symbol: "LW", name: "Lamb Weston", alias: [] },
  { symbol: "LVS", name: "Las Vegas Sands", alias: [] },
  { symbol: "LDOS", name: "Leidos", alias: [] },
  { symbol: "LEN", name: "Lennar", alias: [] },
  { symbol: "LIN", name: "Linde plc", alias: ["Linde"] },
  { symbol: "LYV", name: "Live Nation Entertainment", alias: ["Live Nation"] },
  { symbol: "LKQ", name: "LKQ Corporation", alias: ["LKQ"] },
  { symbol: "LMT", name: "Lockheed Martin", alias: [] },
  { symbol: "L", name: "Loews Corporation", alias: ["Loews"] },
  { symbol: "LOW", name: "Lowe's", alias: [] },
  { symbol: "LULU", name: "Lululemon Athletica", alias: ["Lululemon"] },
  { symbol: "LYB", name: "LyondellBasell", alias: [] },
  { symbol: "MTB", name: "M&T Bank", alias: [] },
  { symbol: "MRO", name: "Marathon Oil", alias: [] },
  { symbol: "MPC", name: "Marathon Petroleum", alias: [] },
  { symbol: "MKTX", name: "MarketAxess", alias: [] },
  { symbol: "MAR", name: "Marriott International", alias: [] },
  { symbol: "MMC", name: "Marsh McLennan", alias: [] },
  { symbol: "MLM", name: "Martin Marietta Materials", alias: ["Martin Marietta"] },
  { symbol: "MAS", name: "Masco", alias: [] },
  { symbol: "MA", name: "Mastercard", alias: [] },
  { symbol: "MTCH", name: "Match Group", alias: [] },
  { symbol: "MKC", name: "McCormick & Company", alias: [] },
  { symbol: "MCD", name: "McDonald's", alias: [] },
  { symbol: "MCK", name: "McKesson", alias: [] },
  { symbol: "MDT", name: "Medtronic", alias: [] },
  { symbol: "MRK", name: "Merck & Co.", alias: [] },
  { symbol: "META", name: "Meta", alias: [] },
  { symbol: "MET", name: "MetLife", alias: [] },
  { symbol: "MTD", name: "Mettler Toledo", alias: [] },
  { symbol: "MGM", name: "MGM Resorts", alias: [] },
  { symbol: "MCHP", name: "Microchip Technology", alias: ["Microchip"] },
  { symbol: "MU", name: "Micron Technology", alias: ["Micron"] },
  { symbol: "MSFT", name: "Microsoft", alias: [] },
  { symbol: "MAA", name: "Mid-America Apartment Communities", alias: [] },
  { symbol: "MRNA", name: "Moderna", alias: [] },
  { symbol: "MHK", name: "Mohawk Industries", alias: ["Mohawk"] },
  { symbol: "MOH", name: "Molina Healthcare", alias: [] },
  { symbol: "TAP", name: "Molson Coors Beverage Company", alias: ["Molson Coors"] },
  { symbol: "MDLZ", name: "Mondelez International", alias: ["Mondelez"] },
  { symbol: "MPWR", name: "Monolithic Power Systems", alias: ["Monolithic"] },
  { symbol: "MNST", name: "Monster Beverage", alias: ["Monster"] },
  { symbol: "MCO", name: "Moody's Corporation", alias: ["Moody's"] },
  { symbol: "MS", name: "Morgan Stanley", alias: [] },
  { symbol: "MOS", name: "Mosaic Company", alias: ["Mosaic"] },
  { symbol: "MSI", name: "Motorola Solutions", alias: [] },
  { symbol: "MSCI", name: "MSCI", alias: [] },
  { symbol: "NDAQ", name: "Nasdaq, Inc.", alias: ["Nasdaq"] },
  { symbol: "NTAP", name: "NetApp", alias: [] },
  { symbol: "NFLX", name: "Netflix", alias: [] },
  { symbol: "NEM", name: "Newmont", alias: [] },
  { symbol: "NWSA", name: "News Corp (Class A)", alias: ["News Corp"] },
  { symbol: "NWS", name: "News Corp (Class B)", alias: ["News Corp B"] },
  { symbol: "NEE", name: "NextEra Energy", alias: ["NextEra"] },
  { symbol: "NKE", name: "Nike Inc.", alias: ["Nike"] },
  { symbol: "NI", name: "NiSource", alias: [] },
  { symbol: "NDSN", name: "Nordson Corporation", alias: ["Nordson"] },
  { symbol: "NSC", name: "Norfolk Southern Railway", alias: ["Norfolk Southern"] },
  { symbol: "NTRS", name: "Northern Trust", alias: [] },
  { symbol: "NOC", name: "Northrop Grumman", alias: [] },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings", alias: ["Norwegian Cruise Line"] },
  { symbol: "NRG", name: "NRG Energy", alias: ["NRG"] },
  { symbol: "NUE", name: "Nucor", alias: [] },
  { symbol: "NVDA", name: "Nvidia", alias: [] },
  { symbol: "NVR", name: "NVR, Inc.", alias: [] },
  { symbol: "NXPI", name: "NXP Semiconductors", alias: [] },
  { symbol: "ORLY", name: "O'Reilly Auto Parts", alias: [] },
  { symbol: "OXY", name: "Occidental Petroleum", alias: ["Occidental"] },
  { symbol: "ODFL", name: "Old Dominion", alias: [] },
  { symbol: "OMC", name: "Omnicom Group", alias: [] },
  { symbol: "ON", name: "ON Semiconductor", alias: [] },
  { symbol: "OKE", name: "ONEOK", alias: [] },
  { symbol: "ORCL", name: "Oracle Corporation", alias: ["Oracle"] },
  { symbol: "OTIS", name: "Otis Worldwide", alias: ["Otis"] },
  { symbol: "PCAR", name: "Paccar", alias: [] },
  { symbol: "PKG", name: "Packaging Corporation of America", alias: ["Packaging"] },
  { symbol: "PANW", name: "Palo Alto Networks", alias: [] },
  { symbol: "PARA", name: "Paramount Global", alias: [] },
  { symbol: "PH", name: "Parker Hannifin", alias: [] },
  { symbol: "PAYX", name: "Paychex", alias: [] },
  { symbol: "PAYC", name: "Paycom", alias: [] },
  { symbol: "PYPL", name: "PayPal", alias: [] },
  { symbol: "PNR", name: "Pentair", alias: [] },
  { symbol: "PEP", name: "PepsiCo", alias: [] },
  { symbol: "PFE", name: "Pfizer", alias: [] },
  { symbol: "PCG", name: "PG&E Corporation", alias: ["PG&E"] },
  { symbol: "PM", name: "Philip Morris International", alias: ["Philip Morris"] },
  { symbol: "PSX", name: "Phillips 66", alias: [] },
  { symbol: "PNW", name: "Pinnacle West", alias: [] },
  { symbol: "PNC", name: "PNC Financial Services", alias: ["PNC"] },
  { symbol: "POOL", name: "Pool Corporation", alias: [] },
  { symbol: "PPG", name: "PPG Industries", alias: ["PPG"] },
  { symbol: "PPL", name: "PPL Corporation", alias: ["PPL"] },
  { symbol: "PFG", name: "Principal Financial Group", alias: ["Principal"] },
  { symbol: "PG", name: "Procter & Gamble", alias: [] },
  { symbol: "PGR", name: "Progressive Corporation", alias: ["Progressive"] },
  { symbol: "PLD", name: "Prologis", alias: [] },
  { symbol: "PRU", name: "Prudential Financial", alias: [] },
  { symbol: "PEG", name: "Public Service Enterprise Group", alias: [] },
  { symbol: "PTC", name: "PTC", alias: [] },
  { symbol: "PSA", name: "Public Storage", alias: [] },
  { symbol: "PHM", name: "PulteGroup", alias: [] },
  { symbol: "QRVO", name: "Qorvo", alias: [] },
  { symbol: "PWR", name: "Quanta Services", alias: [] },
  { symbol: "QCOM", name: "Qualcomm", alias: [] },
  { symbol: "DGX", name: "Quest Diagnostics", alias: [] },
  { symbol: "RL", name: "Ralph Lauren Corporation", alias: ["Ralph Lauren"] },
  { symbol: "RJF", name: "Raymond James", alias: [] },
  { symbol: "RTX", name: "RTX Corporation", alias: [] },
  { symbol: "O", name: "Realty Income", alias: [] },
  { symbol: "REG", name: "Regency Centers", alias: [] },
  { symbol: "REGN", name: "Regeneron", alias: [] },
  { symbol: "RF", name: "Regions Financial Corporation", alias: ["Regions Financial"] },
  { symbol: "RSG", name: "Republic Services", alias: [] },
  { symbol: "RMD", name: "ResMed", alias: [] },
  { symbol: "RVTY", name: "Revvity", alias: [] },
  { symbol: "RHI", name: "Robert Half", alias: [] },
  { symbol: "ROK", name: "Rockwell Automation", alias: [] },
  { symbol: "ROL", name: "Rollins, Inc.", alias: ["Rollins"] },
  { symbol: "ROP", name: "Roper Technologies", alias: ["Roper"] },
  { symbol: "ROST", name: "Ross Stores", alias: [] },
  { symbol: "RCL", name: "Royal Caribbean Group", alias: ["Royal Caribbean"] },
  { symbol: "SPGI", name: "S&P Global", alias: [] },
  { symbol: "CRM", name: "Salesforce", alias: [] },
  { symbol: "SBAC", name: "SBA Communications", alias: [] },
  { symbol: "SLB", name: "Schlumberger", alias: [] },
  { symbol: "STX", name: "Seagate Technology", alias: ["Seagate"] },
  { symbol: "SRE", name: "Sempra Energy", alias: ["Sempra"] },
  { symbol: "NOW", name: "ServiceNow", alias: [] },
  { symbol: "SHW", name: "Sherwin-Williams", alias: [] },
  { symbol: "SPG", name: "Simon Property Group", alias: ["Simon", "Simon Property"] },
  { symbol: "SWKS", name: "Skyworks Solutions", alias: ["Skyworks"] },
  { symbol: "SJM", name: "J.M. Smucker Company", alias: [] },
  { symbol: "SNA", name: "Snap-on", alias: [] },
  { symbol: "SOLV", name: "Solventum", alias: [] },
  { symbol: "SO", name: "Southern Company", alias: ["Southern"] },
  { symbol: "LUV", name: "Southwest Airlines", alias: ["Southwest"] },
  { symbol: "SWK", name: "Stanley Black & Decker", alias: [] },
  { symbol: "SBUX", name: "Starbucks", alias: [] },
  { symbol: "STT", name: "State Street Corporation", alias: [] },
  { symbol: "STLD", name: "Steel Dynamics", alias: [] },
  { symbol: "STE", name: "Steris", alias: [] },
  { symbol: "SYK", name: "Stryker Corporation", alias: ["Stryker"] },
  { symbol: "SMCI", name: "Supermicro", alias: [] },
  { symbol: "SYF", name: "Synchrony Financial", alias: ["Synchrony"] },
  { symbol: "SNPS", name: "Synopsys", alias: [] },
  { symbol: "SYY", name: "Sysco", alias: [] },
  { symbol: "TMUS", name: "T-Mobile US", alias: [] },
  { symbol: "TROW", name: "T. Rowe Price", alias: [] },
  { symbol: "TTWO", name: "Take-Two Interactive", alias: [] },
  { symbol: "TPR", name: "Tapestry, Inc.", alias: ["Tapestry"] },
  { symbol: "TRGP", name: "Targa Resources", alias: [] },
  { symbol: "TGT", name: "Target Corporation", alias: [] },
  { symbol: "TEL", name: "TE Connectivity", alias: [] },
  { symbol: "TDY", name: "Teledyne Technologies", alias: ["Teledyne"] },
  { symbol: "TFX", name: "Teleflex", alias: [] },
  { symbol: "TER", name: "Teradyne", alias: [] },
  { symbol: "TSLA", name: "Tesla", alias: [] },
  { symbol: "TXN", name: "Texas Instruments", alias: [] },
  { symbol: "TXT", name: "Textron", alias: [] },
  { symbol: "TMO", name: "Thermo Fisher Scientific", alias: [] },
  { symbol: "TJX", name: "TJX Companies", alias: ["TJX"] },
  { symbol: "TSCO", name: "Tractor Supply", alias: [] },
  { symbol: "TT", name: "Trane Technologies", alias: ["Trane"] },
  { symbol: "TDG", name: "TransDigm Group", alias: [] },
  { symbol: "TRV", name: "Travelers Companies (The)", alias: [] },
  { symbol: "TRMB", name: "Trimble Inc.", alias: ["Trimble"] },
  { symbol: "TFC", name: "Truist", alias: [] },
  { symbol: "TYL", name: "Tyler Technologies", alias: ["Tyler"] },
  { symbol: "TSN", name: "Tyson Foods", alias: [] },
  { symbol: "USB", name: "U.S. Bank", alias: [] },
  { symbol: "UBER", name: "Uber", alias: [] },
  { symbol: "UDR", name: "UDR, Inc.", alias: [] },
  { symbol: "ULTA", name: "Ulta Beauty", alias: [] },
  { symbol: "UNP", name: "Union Pacific Corporation", alias: ["Union Pacific"] },
  { symbol: "UAL", name: "United Airlines Holdings", alias: ["United Airlines"] },
  { symbol: "UPS", name: "United Parcel Service", alias: ["United Parcel"] },
  { symbol: "URI", name: "United Rentals", alias: [] },
  { symbol: "UNH", name: "UnitedHealth Group", alias: [] },
  { symbol: "UHS", name: "Universal Health Services", alias: [] },
  { symbol: "VLO", name: "Valero Energy", alias: [] },
  { symbol: "VTR", name: "Ventas", alias: [] },
  { symbol: "VLTO", name: "Veralto", alias: [] },
  { symbol: "VRSN", name: "Verisign", alias: [] },
  { symbol: "VRSK", name: "Verisk", alias: [] },
  { symbol: "VZ", name: "Verizon", alias: [] },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", alias: [] },
  { symbol: "VTRS", name: "Viatris", alias: [] },
  { symbol: "VICI", name: "Vici Properties", alias: [] },
  { symbol: "V", name: "Visa Inc.", alias: ["Visa"] },
  { symbol: "VST", name: "Vistra", alias: [] },
  { symbol: "VMC", name: "Vulcan Materials Company", alias: ["Vulcan Materials"] },
  { symbol: "WRB", name: "W. R. Berkley Corporation", alias: ["W. R. Berkley"] },
  { symbol: "GWW", name: "W. W. Grainger", alias: [] },
  { symbol: "WAB", name: "Wabtec", alias: [] },
  { symbol: "WBA", name: "Walgreens Boots Alliance", alias: [] },
  { symbol: "WMT", name: "Walmart", alias: [] },
  { symbol: "DIS", name: "Walt Disney Company", alias: ["Walt Disney"] },
  { symbol: "WBD", name: "Warner Bros. Discovery", alias: [] },
  { symbol: "WM", name: "Waste Management", alias: [] },
  { symbol: "WAT", name: "Waters Corporation", alias: ["Waters"] },
  { symbol: "WEC", name: "WEC Energy Group", alias: [] },
  { symbol: "WFC", name: "Wells Fargo", alias: [] },
  { symbol: "WELL", name: "Welltower", alias: [] },
  { symbol: "WST", name: "West Pharmaceutical Services", alias: ["West Pharmaceutical"] },
  { symbol: "WDC", name: "Western Digital", alias: [] },
  { symbol: "WRK", name: "WestRock", alias: [] },
  { symbol: "WY", name: "Weyerhaeuser", alias: [] },
  { symbol: "WMB", name: "Williams Companies", alias: ["Williams"] },
  { symbol: "WTW", name: "Willis Towers Watson", alias: [] },
  { symbol: "WYNN", name: "Wynn Resorts", alias: ["Wynn"] },
  { symbol: "XEL", name: "Xcel Energy", alias: ["Xcel"] },
  { symbol: "XYL", name: "Xylem Inc.", alias: ["Xylem"] },
  { symbol: "YUM", name: "Yum! Brands", alias: [] },
  { symbol: "ZBRA", name: "Zebra Technologies", alias: ["Zebra"] },
  { symbol: "ZBH", name: "Zimmer Biomet", alias: [] },
  { symbol: "ZTS", name: "Zoetis", alias: [] },
];

export default companies;
